config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from mergecalweb.billing.views import PricingTableView
from mergecalweb.blog.sitemaps import BlogSitemap
from mergecalweb.calendars.views import url_validator
from mergecalweb.core.sitemaps import StaticViewSitemap


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa: F841


sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "meetup/",
        TemplateView.as_view(template_name="pages/meetup.html"),
        name="meetup",
    ),
    path(
        "discord/",
        TemplateView.as_view(template_name="pages/discord.html"),
        name="discord",
    ),
    path(
        "twitch/",
        TemplateView.as_view(template_name="pages/twitch.html"),
        name="twitch",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("mergecalweb.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "calendars/",
        include("mergecalweb.calendars.urls", namespace="calendars"),
        name="calendars",
    ),
    path("billing/", include("mergecalweb.billing.urls", namespace="billing")),
    path("pricing/", PricingTableView.as_view(), name="pricing"),
    path("blog/", include("mergecalweb.blog.urls", namespace="blog")),
    path("validator/", url_validator, name="url_validator"),
    path("tz_detect/", include("tz_detect.urls")),
    path(
        "privacy/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),  # add the robots.txt file
    path(
        "favicon.png",
        RedirectView.as_view(url="/static/images/favicon.png", permanent=True),
    ),
    path(
        "favicon.ico",
        RedirectView.as_view(url="static/images/favicons/favicon.ico", permanent=True),
    ),
    path(
        "cc091514c16021fa4fcd472803a63e5f.txt",
        TemplateView.as_view(
            template_name="cc091514c16021fa4fcd472803a63e5f.txt",
            content_type="text/plain",
        ),
    ),
    path("djstripe/", include("djstripe.urls", namespace="djstripe")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("sentry-debug/", trigger_error, name="sentry-debug"),
    # Health Check
    path("ht/", include("health_check.urls")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

mergecalweb/billing/urls.py
from django.urls import path

from mergecalweb.billing.views import ManageBillingView
from mergecalweb.billing.views import checkout_session_success

app_name = "billing"

urlpatterns = [
    path("manage-billing/", ManageBillingView.as_view(), name="manage_billing"),
    path(
        "success/",
        checkout_session_success,
        name="checkout_session_success",
    ),
]

mergecalweb/blog/urls.py
from django.urls import path

from .views import BlogPostDetailView
from .views import BlogPostListView
from .views import BlogPostTagListView

app_name = "blog"

urlpatterns = [
    path("", BlogPostListView.as_view(), name="list"),
    path("<slug>", BlogPostDetailView.as_view(), name="detail"),
    path("tag/<slug:tag_slug>/", BlogPostTagListView.as_view(), name="tag"),
]

mergecalweb/users/urls.py
from django.urls import path

from .views import account_delete_view
from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~delete/", view=account_delete_view, name="delete"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

mergecalweb/billing/models.py
# Create your models here.

mergecalweb/core/models.py
from django.db import models
from django.utils import timezone


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class SoftDeleteManager(models.Manager):
    """
    soft delete Manager
    https://dev.to/bikramjeetsingh/soft-deletes-in-django-a9j
    """

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class SoftDeleteModel(models.Model):
    """
    soft delete model
    https://dev.to/bikramjeetsingh/soft-deletes-in-django-a9j
    """

    all_objects = models.Manager()

    deleted_at = models.DateTimeField(null=True, default=None)
    objects = SoftDeleteManager()

    class Meta:
        abstract = True

    def soft_delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def restore(self):
        self.deleted_at = None
        self.save()

mergecalweb/billing/views.py
# ruff: noqa: ERA001

import logging

import stripe
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from djstripe.models import Session

from mergecalweb.billing.signals import update_user_subscription_tier

logger = logging.getLogger(__name__)


stripe.api_key = settings.STRIPE_SECRET_KEY


class PricingTableView(TemplateView):
    template_name = "billing/pricing_table.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["price_table_id"] = settings.STRIPE_PRICE_TABLE_ID
        ctx["stripe_public_key"] = settings.STRIPE_PUBLIC_KEY
        if self.request.user.is_authenticated:
            customer = self.request.user.djstripe_customers.first()
            customer_session = stripe.CustomerSession.create(
                customer=customer.id,
                components={"pricing_table": {"enabled": True}},
            )
            ctx["customer_session_id"] = customer_session.client_secret

        user = self.request.user
        if user.is_authenticated:
            logger.info(
                "User accessed pricing table",
                extra={
                    "event": "temp",
                    "user_id": user.pk,
                    "username": user.username,
                    "email": user.email,
                    "current_tier": user.subscription_tier,
                },
            )
        else:
            logger.info(
                "Anonymous user accessed pricing table",
                extra={"event": "pricing_table_view_anonymous"},
            )

        return ctx


class ManageBillingView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        customer = self.request.user.djstripe_customers.first()
        # if self.request.user.is_free_tier:
        #     return reverse("pricing")

        return_url = self.request.build_absolute_uri(
            reverse("users:detail", kwargs={"username": self.request.user.username}),
        )

        user = self.request.user
        logger.info(
            "User accessing billing portal",
            extra={
                "event": "temp",
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
                "customer_id": customer.id,
                "current_tier": user.subscription_tier,
            },
        )

        portal_session = stripe.billing_portal.Session.create(
            customer=customer.id,
            return_url=return_url,
        )
        return portal_session.url


def checkout_session_success(request: HttpRequest) -> HttpResponse:
    if request.htmx:
        session_id = request.GET.get("session_id")

        if not session_id:
            return JsonResponse({"error": "No session ID provided."}, status=400)

        try:
            session: Session = Session._get_or_retrieve(session_id)  # noqa: SLF001
        except stripe.error.StripeError as e:
            return JsonResponse({"error": str(e)}, status=400)

        if request.user.is_authenticated:
            update_user_subscription_tier(request.user, session.subscription)
            logger.info(
                "Checkout session retrieved and user tier updated",
                extra={
                    "event": "temp",
                    "user_id": request.user.pk,
                    "username": request.user.username,
                    "email": request.user.email,
                    "session_id": session_id,
                    "customer_id": session.customer.id,
                    "subscription_id": session.subscription.id,
                },
            )
        else:
            logger.info(
                "Checkout session retrieved for unauthenticated user",
                extra={
                    "event": "checkout_session_retrieved_anonymous",
                    "session_id": session_id,
                },
            )

        context = {
            "session": session,
            "customer": session.customer,
            "subscription": session.subscription,
        }
        return render(request, "billing/_success.html", context)

    user = request.user
    if user.is_authenticated:
        logger.info(
            "User accessed checkout success page",
            extra={
                "event": "temp",
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
            },
        )
    else:
        logger.info(
            "Anonymous user accessed checkout success page",
            extra={"event": "checkout_success_page_view_anonymous"},
        )

    return render(request, "billing/success.html")

mergecalweb/blog/views.py
import logging

from django.views.generic import DetailView
from django.views.generic import ListView

from mergecalweb.core.logging_events import LogEvent

from .models import BlogPost

# Get an instance of a logger
logger = logging.getLogger(__name__)


class BlogPostListView(ListView):
    model = BlogPost
    queryset = BlogPost.objects.filter(published=True)
    template_name = "blog/list.html"
    context_object_name = "blog_posts"
    paginate_by = 15  # that is all it takes to add pagination in a Class-Based View

    def get(self, request, *args, **kwargs):
        extra = {"event": LogEvent.PAGE_VIEW, "view_type": "blog_post_list"}
        if request.user.is_authenticated:
            extra["user_id"] = request.user.pk
            extra["email"] = request.user.email
        logger.info("Blog post list viewed", extra=extra)
        return super().get(request, *args, **kwargs)


class BlogPostDetailView(DetailView):
    model = BlogPost
    queryset = BlogPost.objects.filter(published=True)
    template_name = "blog/detail.html"
    context_object_name = "blog_post"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        blog_post = self.get_object()
        extra = {
            "event": LogEvent.PAGE_VIEW,
            "view_type": "blog_post_detail",
            "blog_post_slug": blog_post.slug,
            "blog_post_title": blog_post.title,
        }
        if request.user.is_authenticated:
            extra["user_id"] = request.user.pk
            extra["email"] = request.user.email
        logger.info("Blog post viewed", extra=extra)
        return response


class BlogPostTagListView(ListView):
    model = BlogPost
    template_name = "blog/list.html"  # You can reuse the list template
    context_object_name = "blog_posts"

    def get_queryset(self):
        return BlogPost.objects.published().filter(tags__slug=self.kwargs["tag_slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_tag"] = self.kwargs["tag_slug"]
        return context

mergecalweb/integrations/views.py
# Create your views here.

mergecalweb/users/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from mergecalweb.billing.tasks import update_stripe_subscription
from mergecalweb.core.logging_events import LogEvent
from mergecalweb.users.models import User

logger = logging.getLogger(__name__)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        profile_username = kwargs.get("username")
        viewer = request.user

        logger.debug(
            "User accessing profile page",
            extra={
                "event": LogEvent.PAGE_VIEW,
                "view_type": "profile",
                "profile_username": profile_username,
                "viewer_id": viewer.pk,
                "viewer_username": viewer.username,
                "is_own_profile": profile_username == viewer.username,
            },
        )

        response = super().get(request, *args, **kwargs)

        logger.info(
            "Triggering subscription sync for profile user",
            extra={
                "event": LogEvent.USER_PROFILE_SUBSCRIPTION_SYNC,
                "user_id": self.object.pk,
                "username": self.object.username,
                "email": self.object.email,
                "current_tier": self.object.subscription_tier,
            },
        )
        update_stripe_subscription(self.object.id)

        return response


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None = None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user

    def form_valid(self, form):
        user = self.request.user
        old_name = user.name
        new_name = form.cleaned_data.get("name")

        logger.info(
            "User updated profile information",
            extra={
                "event": LogEvent.USER_PROFILE_UPDATED,
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
                "old_name": old_name,
                "new_name": new_name,
            },
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("calendars:calendar_list")


user_redirect_view = UserRedirectView.as_view()

mergecalweb/templates/users/user_confirm_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
  {% trans "Delete Account" %}
{% endblock title %}
{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <div class="card shadow-sm border-danger">
          <div class="card-header bg-danger text-white">
            <h2 class="mb-0">
              <i class="bi bi-exclamation-triangle-fill me-2"></i>
              {% trans "Delete Your Account" %}
            </h2>
          </div>
          <div class="card-body">
            <!-- Warning Banner -->
            <div class="alert alert-danger" role="alert">
              <h4 class="alert-heading">
                <i class="bi bi-exclamation-octagon me-2"></i>
                {% trans "Warning: This action is permanent and cannot be undone!" %}
              </h4>
              <p class="mb-0">
                {% trans "Once you delete your account, there is no going back. All your data will be permanently removed from our servers." %}
              </p>
            </div>
            <!-- Deletion Preview -->
            <div class="mt-4 mb-4">
              <h4 class="mb-3">{% trans "The following will be permanently deleted:" %}</h4>
              <div class="card bg-body-secondary">
                <div class="card-body">
                  <ul class="list-unstyled mb-2">
                    <li class="mb-2">
                      <i class="bi bi-person-fill text-danger me-2"></i>
                      <strong>{% trans "Your user account:" %}</strong> {{ request.user.email }}
                    </li>
                    {% if total_calendars > 0 %}
                      <li class="mb-2">
                        <i class="bi bi-calendar-fill text-danger me-2"></i>
                        <strong>{{ total_calendars }}
                          {% if total_calendars == 1 %}
                            {% trans "Calendar" %}
                          {% else %}
                            {% trans "Calendars" %}
                          {% endif %}
                        :</strong>
                        <ul class="mt-2 mb-2">
                          {% for calendar in calendars %}
                            <li>
                              <strong>"{{ calendar.name }}"</strong>
                              ({{ calendar.calendarOf.count }}
                              {% if calendar.calendarOf.count == 1 %}
                                {% trans "source" %}
                              {% else %}
                                {% trans "sources" %}
                              {% endif %}
                              )
                            </li>
                          {% endfor %}
                        </ul>
                      </li>
                      <li class="mb-2">
                        <i class="bi bi-link-45deg text-danger me-2"></i>
                        <strong>{{ total_sources }}
                          {% if total_sources == 1 %}
                            {% trans "Source" %}
                          {% else %}
                            {% trans "Sources" %}
                          {% endif %}
                        </strong> {% trans "(total)" %}
                      </li>
                    {% else %}
                      <li class="mb-2">
                        <i class="bi bi-calendar text-body-secondary me-2"></i>
                        <em>{% trans "No calendars to delete" %}</em>
                      </li>
                    {% endif %}
                  </ul>
                  <hr />
                  <p class="text-body-secondary mb-0">
                    <i class="bi bi-info-circle me-2"></i>
                    <small>{% trans "Your payment history and invoices will be retained for legal compliance." %}</small>
                  </p>
                </div>
              </div>
            </div>
            <!-- Deletion Form -->
            <div class="mt-4">
              <h4 class="mb-3">{% trans "Confirm Account Deletion" %}</h4>
              <form method="post" action="{% url 'users:delete' %}">
                {% csrf_token %}
                <!-- Password Field -->
                <div class="mb-3">
                  {{ form.password.label_tag }}
                  {{ form.password }}
                  {% if form.password.help_text %}<small class="form-text text-muted">{{ form.password.help_text }}</small>{% endif %}
                  {% if form.password.errors %}<div class="invalid-feedback d-block">{{ form.password.errors }}</div>{% endif %}
                </div>
                <!-- Confirmation Checkbox -->
                <div class="mb-4 form-check">
                  {{ form.confirm_deletion }}
                  {{ form.confirm_deletion.label_tag }}
                  {% if form.confirm_deletion.errors %}
                    <div class="invalid-feedback d-block">{{ form.confirm_deletion.errors }}</div>
                  {% endif %}
                </div>
                <!-- Action Buttons -->
                <div class="d-flex gap-2">
                  <a href="{% url 'users:detail' request.user.username %}"
                     class="btn btn-secondary">
                    <i class="bi bi-x-circle me-1"></i>
                    {% trans "Cancel" %}
                  </a>
                  <button type="submit" class="btn btn-danger">
                    <i class="bi bi-trash-fill me-1"></i>
                    {% trans "Delete My Account" %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- Additional Help -->
        <div class="mt-3 text-center text-body-secondary">
          <small>
            {% trans "Need help? Contact us at" %} <a href="mailto:support@mergecal.com">support@mergecal.com</a>
          </small>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mergecalweb/templates/users/user_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  User: {{ object.username }}
{% endblock title %}
{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow-sm">
          <div class="card-header bg-primary text-white">
            <h2 class="mb-0">{{ object.username }}</h2>
          </div>
          <div class="card-body">
            {% if object.name %}<p class="lead">{{ object.name }}</p>{% endif %}
            <p>
              Subscription Tier: <strong>{{ object.get_subscription_tier_display }}</strong>
            </p>
            {% if object == request.user %}
              <!-- Action buttons -->
              <div class="mt-4">
                <a class="btn btn-outline-primary me-2"
                   href="{% url 'users:update' %}"
                   role="button">My Info</a>
                <a class="btn btn-outline-primary me-2"
                   href="{% url 'account_email' %}"
                   role="button">E-Mail</a>
                <a class="btn btn-outline-primary me-2"
                   href="{% url 'account_change_password' %}"
                   role="button">Change Password</a>
                <a class="btn btn-outline-primary me-2"
                   href="{% url 'mfa_index' %}"
                   role="button">MFA</a>
                <!-- Manage Billing Form -->
                <form method="post"
                      action="{% url 'billing:manage_billing' %}"
                      class="d-inline">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-primary">Manage billing</button>
                </form>
                <!-- End Manage Billing Form -->
              </div>
              <!-- End Action buttons -->
              <!-- Danger Zone -->
              <div class="mt-5 pt-4 border-top border-danger">
                <h5 class="text-danger mb-3">
                  <i class="bi bi-exclamation-triangle-fill me-2"></i>Danger Zone
                </h5>
                <p class="text-body-secondary">Once you delete your account, there is no going back. Please be certain.</p>
                <a class="btn btn-outline-danger"
                   href="{% url 'users:delete' %}"
                   role="button">
                  <i class="bi bi-trash me-1"></i>Delete Account
                </a>
              </div>
              <!-- End Danger Zone -->
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

mergecalweb/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  {{ user.username }}
{% endblock title %}
{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock content %}