config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from mergecalweb.billing.views import PricingTableView
from mergecalweb.blog.sitemaps import BlogSitemap
from mergecalweb.calendars.views import url_validator
from mergecalweb.core.sitemaps import StaticViewSitemap


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa: F841


sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "meetup/",
        TemplateView.as_view(template_name="pages/meetup.html"),
        name="meetup",
    ),
    path(
        "discord/",
        TemplateView.as_view(template_name="pages/discord.html"),
        name="discord",
    ),
    path(
        "twitch/",
        TemplateView.as_view(template_name="pages/twitch.html"),
        name="twitch",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("mergecalweb.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "calendars/",
        include("mergecalweb.calendars.urls", namespace="calendars"),
        name="calendars",
    ),
    path("billing/", include("mergecalweb.billing.urls", namespace="billing")),
    path("pricing/", PricingTableView.as_view(), name="pricing"),
    path("blog/", include("mergecalweb.blog.urls", namespace="blog")),
    path("validator/", url_validator, name="url_validator"),
    path("tz_detect/", include("tz_detect.urls")),
    path(
        "privacy/",
        TemplateView.as_view(template_name="pages/privacy.html"),
        name="privacy",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="pages/terms.html"),
        name="terms",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),  # add the robots.txt file
    path(
        "favicon.png",
        RedirectView.as_view(url="/static/images/favicon.png", permanent=True),
    ),
    path(
        "favicon.ico",
        RedirectView.as_view(url="static/images/favicons/favicon.ico", permanent=True),
    ),
    path(
        "cc091514c16021fa4fcd472803a63e5f.txt",
        TemplateView.as_view(
            template_name="cc091514c16021fa4fcd472803a63e5f.txt",
            content_type="text/plain",
        ),
    ),
    path("djstripe/", include("djstripe.urls", namespace="djstripe")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("sentry-debug/", trigger_error, name="sentry-debug"),
    # Health Check
    path("ht/", include("health_check.urls")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
        path("__reload__/", include("django_browser_reload.urls")),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

mergecalweb/billing/urls.py
from django.urls import path

from mergecalweb.billing.views import ManageBillingView
from mergecalweb.billing.views import checkout_session_success

app_name = "billing"

urlpatterns = [
    path("manage-billing/", ManageBillingView.as_view(), name="manage_billing"),
    path(
        "success/",
        checkout_session_success,
        name="checkout_session_success",
    ),
]

mergecalweb/blog/urls.py
from django.urls import path

from .views import BlogPostDetailView
from .views import BlogPostListView
from .views import BlogPostTagListView

app_name = "blog"

urlpatterns = [
    path("", BlogPostListView.as_view(), name="list"),
    path("<slug>", BlogPostDetailView.as_view(), name="detail"),
    path("tag/<slug:tag_slug>/", BlogPostTagListView.as_view(), name="tag"),
]

mergecalweb/users/urls.py
from django.urls import path

from .views import account_delete_view
from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~delete/", view=account_delete_view, name="delete"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

mergecalweb/billing/models.py
# Create your models here.

mergecalweb/core/models.py
from django.db import models
from django.utils import timezone


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class SoftDeleteManager(models.Manager):
    """
    soft delete Manager
    https://dev.to/bikramjeetsingh/soft-deletes-in-django-a9j
    """

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class SoftDeleteModel(models.Model):
    """
    soft delete model
    https://dev.to/bikramjeetsingh/soft-deletes-in-django-a9j
    """

    all_objects = models.Manager()

    deleted_at = models.DateTimeField(null=True, default=None)
    objects = SoftDeleteManager()

    class Meta:
        abstract = True

    def soft_delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def restore(self):
        self.deleted_at = None
        self.save()

mergecalweb/billing/views.py
# ruff: noqa: ERA001

import logging

import stripe
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from djstripe.models import Session

from mergecalweb.billing.signals import update_user_subscription_tier

logger = logging.getLogger(__name__)


stripe.api_key = settings.STRIPE_SECRET_KEY


class PricingTableView(TemplateView):
    template_name = "billing/pricing_table.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["price_table_id"] = settings.STRIPE_PRICE_TABLE_ID
        ctx["stripe_public_key"] = settings.STRIPE_PUBLIC_KEY
        if self.request.user.is_authenticated:
            customer = self.request.user.djstripe_customers.first()
            customer_session = stripe.CustomerSession.create(
                customer=customer.id,
                components={"pricing_table": {"enabled": True}},
            )
            ctx["customer_session_id"] = customer_session.client_secret

        user = self.request.user
        if user.is_authenticated:
            logger.info(
                "User accessed pricing table",
                extra={
                    "event": "temp",
                    "user_id": user.pk,
                    "username": user.username,
                    "email": user.email,
                    "current_tier": user.subscription_tier,
                },
            )
        else:
            logger.info(
                "Anonymous user accessed pricing table",
                extra={"event": "pricing_table_view_anonymous"},
            )

        return ctx


class ManageBillingView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        customer = self.request.user.djstripe_customers.first()
        # if self.request.user.is_free_tier:
        #     return reverse("pricing")

        return_url = self.request.build_absolute_uri(
            reverse("users:detail", kwargs={"username": self.request.user.username}),
        )

        user = self.request.user
        logger.info(
            "User accessing billing portal",
            extra={
                "event": "temp",
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
                "customer_id": customer.id,
                "current_tier": user.subscription_tier,
            },
        )

        portal_session = stripe.billing_portal.Session.create(
            customer=customer.id,
            return_url=return_url,
        )
        return portal_session.url


def checkout_session_success(request: HttpRequest) -> HttpResponse:
    if request.htmx:
        session_id = request.GET.get("session_id")

        if not session_id:
            return JsonResponse({"error": "No session ID provided."}, status=400)

        try:
            session: Session = Session._get_or_retrieve(session_id)  # noqa: SLF001
        except stripe.error.StripeError as e:
            return JsonResponse({"error": str(e)}, status=400)

        if request.user.is_authenticated:
            update_user_subscription_tier(request.user, session.subscription)
            logger.info(
                "Checkout session retrieved and user tier updated",
                extra={
                    "event": "temp",
                    "user_id": request.user.pk,
                    "username": request.user.username,
                    "email": request.user.email,
                    "session_id": session_id,
                    "customer_id": session.customer.id,
                    "subscription_id": session.subscription.id,
                },
            )
        else:
            logger.info(
                "Checkout session retrieved for unauthenticated user",
                extra={
                    "event": "checkout_session_retrieved_anonymous",
                    "session_id": session_id,
                },
            )

        context = {
            "session": session,
            "customer": session.customer,
            "subscription": session.subscription,
        }
        return render(request, "billing/_success.html", context)

    user = request.user
    if user.is_authenticated:
        logger.info(
            "User accessed checkout success page",
            extra={
                "event": "temp",
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
            },
        )
    else:
        logger.info(
            "Anonymous user accessed checkout success page",
            extra={"event": "checkout_success_page_view_anonymous"},
        )

    return render(request, "billing/success.html")

mergecalweb/blog/views.py
import logging

from django.views.generic import DetailView
from django.views.generic import ListView

from mergecalweb.core.logging_events import LogEvent

from .models import BlogPost

# Get an instance of a logger
logger = logging.getLogger(__name__)


class BlogPostListView(ListView):
    model = BlogPost
    queryset = BlogPost.objects.filter(published=True)
    template_name = "blog/list.html"
    context_object_name = "blog_posts"
    paginate_by = 15  # that is all it takes to add pagination in a Class-Based View

    def get(self, request, *args, **kwargs):
        extra = {"event": LogEvent.PAGE_VIEW, "view_type": "blog_post_list"}
        if request.user.is_authenticated:
            extra["user_id"] = request.user.pk
            extra["email"] = request.user.email
        logger.info("Blog post list viewed", extra=extra)
        return super().get(request, *args, **kwargs)


class BlogPostDetailView(DetailView):
    model = BlogPost
    queryset = BlogPost.objects.filter(published=True)
    template_name = "blog/detail.html"
    context_object_name = "blog_post"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        blog_post = self.get_object()
        extra = {
            "event": LogEvent.PAGE_VIEW,
            "view_type": "blog_post_detail",
            "blog_post_slug": blog_post.slug,
            "blog_post_title": blog_post.title,
        }
        if request.user.is_authenticated:
            extra["user_id"] = request.user.pk
            extra["email"] = request.user.email
        logger.info("Blog post viewed", extra=extra)
        return response


class BlogPostTagListView(ListView):
    model = BlogPost
    template_name = "blog/list.html"  # You can reuse the list template
    context_object_name = "blog_posts"

    def get_queryset(self):
        return BlogPost.objects.published().filter(tags__slug=self.kwargs["tag_slug"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_tag"] = self.kwargs["tag_slug"]
        return context

mergecalweb/integrations/views.py
# Create your views here.

mergecalweb/users/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from mergecalweb.billing.tasks import update_stripe_subscription
from mergecalweb.core.logging_events import LogEvent
from mergecalweb.users.models import User

logger = logging.getLogger(__name__)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        profile_username = kwargs.get("username")
        viewer = request.user

        logger.debug(
            "User accessing profile page",
            extra={
                "event": LogEvent.PAGE_VIEW,
                "view_type": "profile",
                "profile_username": profile_username,
                "viewer_id": viewer.pk,
                "viewer_username": viewer.username,
                "is_own_profile": profile_username == viewer.username,
            },
        )

        response = super().get(request, *args, **kwargs)

        logger.info(
            "Triggering subscription sync for profile user",
            extra={
                "event": LogEvent.USER_PROFILE_SUBSCRIPTION_SYNC,
                "user_id": self.object.pk,
                "username": self.object.username,
                "email": self.object.email,
                "current_tier": self.object.subscription_tier,
            },
        )
        update_stripe_subscription(self.object.id)

        return response


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None = None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user

    def form_valid(self, form):
        user = self.request.user
        old_name = user.name
        new_name = form.cleaned_data.get("name")

        logger.info(
            "User updated profile information",
            extra={
                "event": LogEvent.USER_PROFILE_UPDATED,
                "user_id": user.pk,
                "username": user.username,
                "email": user.email,
                "old_name": old_name,
                "new_name": new_name,
            },
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("calendars:calendar_list")


user_redirect_view = UserRedirectView.as_view()

mergecalweb/templates/blog/detail.html
{% extends "base.html" %}

{% load i18n static %}
{% load social_share %}

{% block title %}
  {{ blog_post.title }} | MergeCal Blog
{% endblock title %}
{% block og_title %}
  {{ blog_post.title }} | MergeCal Blog
{% endblock og_title %}
{% block og_description %}
  {{ blog_post.description|truncatewords:30 }}
{% endblock og_description %}
{% block meta_description %}
  {{ blog_post.description|truncatewords:30 }}
{% endblock meta_description %}
{% block twitter_title %}
  {{ blog_post.title }} | MergeCal Blog
{% endblock twitter_title %}
{% block twitter_description %}
  {{ blog_post.description|truncatewords:30 }}
{% endblock twitter_description %}
{% if blog_post.image %}
  {% block og_image %}
    {{ blog_post.image.url }}
  {% endblock og_image %}
  {% block twitter_image %}
    {{ blog_post.image.url }}
  {% endblock twitter_image %}
{% endif %}
{% block meta_keywords %}
  {{ blog_post.keywords }}
{% endblock meta_keywords %}
{% block css %}
  {{ block.super }}
  <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism.min.css" />
{% endblock css %}
{% block content %}
  <article class="container my-5"
           itemscope
           itemtype="https://schema.org/BlogPosting">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        {% if blog_post.image %}
          <img src="{{ blog_post.image.url }}"
               class="img-fluid rounded mb-4"
               alt="{{ blog_post.title }}"
               itemprop="image" />
        {% endif %}
        <header class="mb-4">
          <h1 class="display-4 fw-bold" itemprop="headline">{{ blog_post.title }}</h1>
          <div class="d-flex flex-wrap align-items-center text-muted mb-3">
            <span class="me-3">
              <i class="bi bi-calendar3"></i>
              <time datetime="{{ blog_post.pub_date|date:'Y-m-d' }}"
                    itemprop="datePublished">
                {{ blog_post.pub_date|date:"F j, Y" }}
              </time>
            </span>
            <span class="me-3">
              <i class="bi bi-clock"></i> {{ blog_post.get_reading_time }} min read
            </span>
            {% if blog_post.author %}
              <span itemprop="author" itemscope itemtype="https://schema.org/Person">
                <i class="bi bi-person"></i>
                <span itemprop="name">{{ blog_post.author.get_full_name }}</span>
              </span>
            {% endif %}
          </div>
          {% if blog_post.tags.all %}
            <div class="mb-3">
              {% for tag in blog_post.tags.all %}
                <a href="{% url 'blog:tag' tag.slug %}"
                   class="badge bg-secondary text-decoration-none">{{ tag.name }}</a>
              {% endfor %}
            </div>
          {% endif %}
        </header>
        <nav class="card mb-4">
          <div class="card-header">
            <h2 class="h5 mb-0">Table of Contents</h2>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mb-0" id="toc">
            </ul>
          </div>
        </nav>
        <div class="blog-content mb-5" itemprop="articleBody">{{ blog_post.text|safe }}</div>
        <footer class="border-top pt-4 mt-4">
          <div class="row align-items-center">
            <div class="mt-4 mb-5">
              <h3 class="h5 mb-3">Share this post</h3>
              <div class="d-flex flex-wrap gap-2">
                {% post_to_facebook object_or_url '<i class="bi bi-facebook me-2"></i>Share on Facebook' %}
                {% post_to_twitter "Check out this post: {{ blog_post.title }}" object_or_url '<i class="bi bi-twitter me-2"></i>Share on Twitter' %}
                {% post_to_linkedin object_or_url %}
                {% post_to_whatsapp object_or_url link_text='<i class="bi bi-whatsapp me-2"></i>Share on WhatsApp' %}
                {% post_to_telegram object_or_url link_text='<i class="bi bi-telegram me-2"></i>Share on Telegram' %}
              </div>
            </div>
            <div class="col-md-6 text-md-end">
              <a href="{% url 'blog:list' %}" class="btn btn-outline-primary">
                <i class="bi bi-arrow-left"></i> Back to Blog
              </a>
            </div>
          </div>
        </footer>
        {% if blog_post.author %}
          <section class="card mt-5">
            <div class="card-body">
              <h2 class="h4 card-title">About the Author</h2>
              <div class="d-flex align-items-center">
                {% if blog_post.author.profile_picture %}
                  <img src="{{ blog_post.author.profile_picture.url }}"
                       class="rounded-circle me-3"
                       width="64"
                       height="64"
                       alt="{{ blog_post.author.get_full_name }}" />
                {% endif %}
                <div>
                  <h3 class="h5 mb-1">{{ blog_post.author.get_full_name }}</h3>
                  <p class="mb-0">{{ blog_post.author.bio|truncatewords:30 }}</p>
                </div>
              </div>
            </div>
          </section>
        {% endif %}
        {% with related_posts=blog_post.get_related_posts %}
          {% if related_posts %}
            <section class="mt-5">
              <h2 class="h3 mb-4">Related Posts</h2>
              <div class="row row-cols-1 row-cols-md-3 g-4">
                {% for related_post in related_posts %}
                  <div class="col">
                    <div class="card h-100">
                      {% if related_post.image %}
                        <img src="{{ related_post.image.url }}"
                             class="card-img-top"
                             alt="{{ related_post.title }}" />
                      {% endif %}
                      <div class="card-body">
                        <h3 class="h5 card-title">
                          <a href="{{ related_post.get_absolute_url }}"
                             class="text-decoration-none text-dark">{{ related_post.title }}</a>
                        </h3>
                        <p class="card-text">{{ related_post.description|truncatewords:20 }}</p>
                      </div>
                      <div class="card-footer bg-transparent">
                        <small class="text-muted">{{ related_post.pub_date|date:"F j, Y" }}</small>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </section>
          {% endif %}
        {% endwith %}
      </div>
    </div>
  </article>
{% endblock content %}
{% block inline_javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/prism.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/autoloader/prism-autoloader.min.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      // Generate table of contents
      const headers = document.querySelectorAll('.blog-content h2, .blog-content h3');
      const toc = document.getElementById('toc');
      headers.forEach((header, index) => {
        const li = document.createElement('li');
        const a = document.createElement('a');
        const id = `section-${index}`;
        header.id = id;
        a.href = `#${id}`;
        a.textContent = header.textContent;
        a.className = header.tagName === 'H3' ? 'ms-3' : '';
        li.appendChild(a);
        toc.appendChild(li);
      });

      // Highlight code blocks
      Prism.highlightAll();
    });
  </script>
{% endblock inline_javascript %}
{% block structured_data %}
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "headline": "{{ blog_post.title }}",
      "image": "{% if blog_post.image %}{{ blog_post.image.url }}{% else %}{{ request.scheme }}://{{ request.get_host }}{% static 'images/default-blog-image.jpg' %}{% endif %}",
      "datePublished": "{{ blog_post.pub_date|date:'c' }}",
      "dateModified": "{{ blog_post.modified|date:'c' }}",
      "author": {
        "@type": "Person",
        "name": "{% if blog_post.author %}{{ blog_post.author.get_full_name }}{% else %}MergeCal Team{% endif %}"
      },
      "publisher": {
        "@type": "Organization",
        "name": "MergeCal",
        "logo": {
          "@type": "ImageObject",
          "url": "{{ request.scheme }}://{{ request.get_host }}{% static 'images/mergecal-logo.png' %}"
        }
      },
      "description": "{{ blog_post.description }}",
      "keywords": "{{ blog_post.keyword_list|join:', ' }}",
      "wordCount": "{{ blog_post.text|wordcount }}",
      "url": "{{ request.build_absolute_uri }}"
    }
  </script>
{% endblock structured_data %}